import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import { ProviderTheme } from "../providers/ThemeProvider";
import Sidebar from "@/components/shared/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <ProviderTheme>
          {/* <SessionProvider> */}
            <div className="grid grid-cols-6 h-[calc(100vh-24px)] md:h-screen lg:p-10 gap-x-4">
              <Sidebar />
              {/* <GlobalProvider> */}
                {children}
              {/* </GlobalProvider> */}
            </div>
          {/* </SessionProvider> */}
        </ProviderTheme>
      </body>
    </html>
  );
}